# theme: jekyll-theme-leap-day

# Site settings
title: AI-Sys Fa19
email: jegonzal@berkeley.edu 
author:
description: AI-Sys Fa19 Course Website


baseurl: /cs294-ai-sys-fa19

# Build settings
# permalink: :title/
sass:
  sass_dir: css

