# theme: jekyll-theme-leap-day

# Site settings
title: CS262B Sp20
email: culler@berkeley.edu 
author:
description: CS262B Sp20 Course Website


baseurl: /cs262b-sp20

# Build settings
# permalink: :title/
sass:
  sass_dir: css

